/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaticanApprovedMarianApparitionsRouteImport } from './routes/vatican-approved-marian-apparitions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as PrayersRouteImport } from './routes/prayers'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MapRouteImport } from './routes/map'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrayersSlugRouteImport } from './routes/prayers.$slug'
import { Route as ApparitionSlugRouteImport } from './routes/apparition.$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const VaticanApprovedMarianApparitionsRoute =
  VaticanApprovedMarianApparitionsRouteImport.update({
    id: '/vatican-approved-marian-apparitions',
    path: '/vatican-approved-marian-apparitions',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayersRoute = PrayersRouteImport.update({
  id: '/prayers',
  path: '/prayers',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayersSlugRoute = PrayersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PrayersRoute,
} as any)
const ApparitionSlugRoute = ApparitionSlugRouteImport.update({
  id: '/apparition/$slug',
  path: '/apparition/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/mcp': typeof McpRoute
  '/prayers': typeof PrayersRouteWithChildren
  '/saved': typeof SavedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vatican-approved-marian-apparitions': typeof VaticanApprovedMarianApparitionsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/apparition/$slug': typeof ApparitionSlugRoute
  '/prayers/$slug': typeof PrayersSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/mcp': typeof McpRoute
  '/prayers': typeof PrayersRouteWithChildren
  '/saved': typeof SavedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vatican-approved-marian-apparitions': typeof VaticanApprovedMarianApparitionsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/apparition/$slug': typeof ApparitionSlugRoute
  '/prayers/$slug': typeof PrayersSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/mcp': typeof McpRoute
  '/prayers': typeof PrayersRouteWithChildren
  '/saved': typeof SavedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vatican-approved-marian-apparitions': typeof VaticanApprovedMarianApparitionsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/apparition/$slug': typeof ApparitionSlugRoute
  '/prayers/$slug': typeof PrayersSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/map'
    | '/mcp'
    | '/prayers'
    | '/saved'
    | '/sitemap.xml'
    | '/vatican-approved-marian-apparitions'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/apparition/$slug'
    | '/prayers/$slug'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/map'
    | '/mcp'
    | '/prayers'
    | '/saved'
    | '/sitemap.xml'
    | '/vatican-approved-marian-apparitions'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/apparition/$slug'
    | '/prayers/$slug'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/map'
    | '/mcp'
    | '/prayers'
    | '/saved'
    | '/sitemap.xml'
    | '/vatican-approved-marian-apparitions'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/apparition/$slug'
    | '/prayers/$slug'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MapRoute: typeof MapRoute
  McpRoute: typeof McpRoute
  PrayersRoute: typeof PrayersRouteWithChildren
  SavedRoute: typeof SavedRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VaticanApprovedMarianApparitionsRoute: typeof VaticanApprovedMarianApparitionsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApparitionSlugRoute: typeof ApparitionSlugRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vatican-approved-marian-apparitions': {
      id: '/vatican-approved-marian-apparitions'
      path: '/vatican-approved-marian-apparitions'
      fullPath: '/vatican-approved-marian-apparitions'
      preLoaderRoute: typeof VaticanApprovedMarianApparitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayers': {
      id: '/prayers'
      path: '/prayers'
      fullPath: '/prayers'
      preLoaderRoute: typeof PrayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayers/$slug': {
      id: '/prayers/$slug'
      path: '/$slug'
      fullPath: '/prayers/$slug'
      preLoaderRoute: typeof PrayersSlugRouteImport
      parentRoute: typeof PrayersRoute
    }
    '/apparition/$slug': {
      id: '/apparition/$slug'
      path: '/apparition/$slug'
      fullPath: '/apparition/$slug'
      preLoaderRoute: typeof ApparitionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PrayersRouteChildren {
  PrayersSlugRoute: typeof PrayersSlugRoute
}

const PrayersRouteChildren: PrayersRouteChildren = {
  PrayersSlugRoute: PrayersSlugRoute,
}

const PrayersRouteWithChildren =
  PrayersRoute._addFileChildren(PrayersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MapRoute: MapRoute,
  McpRoute: McpRoute,
  PrayersRoute: PrayersRouteWithChildren,
  SavedRoute: SavedRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VaticanApprovedMarianApparitionsRoute: VaticanApprovedMarianApparitionsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApparitionSlugRoute: ApparitionSlugRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
